[package]
name = "tomatwo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
rand = "0.8"
memmap2 = "0.5"
rayon = "1.5"
tempfile = "3.2"